/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppConfig: typeof import('./src/components/AppConfig.vue')['default']
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    AppTopbar: typeof import('./src/components/AppTopbar.vue')['default']
    Button: typeof import('primevue/button')['default']
    FileUpload: typeof import('primevue/fileupload')['default']
    Graph2DWidget: typeof import('./src/components/dashboard/Graph2DWidget.vue')['default']
    Graph2DWidgetAlt: typeof import('./src/components/dashboard/Graph2DWidgetAlt.vue')['default']
    Graph3DWidget: typeof import('./src/components/dashboard/Graph3DWidget.vue')['default']
    GraphActivityWidget: typeof import('./src/components/dashboard/GraphActivityWidget.vue')['default']
    GraphConfigWidget: typeof import('./src/components/dashboard/GraphConfigWidget.vue')['default']
    GraphDataTableWidget: typeof import('./src/components/dashboard/GraphDataTableWidget.vue')['default']
    GraphStatsWidget: typeof import('./src/components/dashboard/GraphStatsWidget.vue')['default']
    GraphTrendWidget: typeof import('./src/components/dashboard/GraphTrendWidget.vue')['default']
    IconField: typeof import('primevue/iconfield')['default']
    InputIcon: typeof import('primevue/inputicon')['default']
    InputNumber: typeof import('primevue/inputnumber')['default']
    InputText: typeof import('primevue/inputtext')['default']
    LoadingDialog: typeof import('./src/components/dashboard/LoadingDialog.vue')['default']
    Message: typeof import('primevue/message')['default']
    SelectButton: typeof import('primevue/selectbutton')['default']
    Tag: typeof import('primevue/tag')['default']
    Toast: typeof import('primevue/toast')['default']
  }
  export interface ComponentCustomProperties {
    StyleClass: typeof import('primevue/styleclass')['default']
  }
}
